export const STATE_CHOICES = [
  { value: "SC", choice: "Santa Catarina" },
  { value: "RS", choice: "Rio Grande do Sul" },
  { value: "PR", choice: "Paraná" },
  { value: "SP", choice: "São Paulo" },
  { value: "RJ", choice: "Rio de Janeiro" },
  { value: "DF", choice: "Distrito Federal" },
  { value: "MT", choice: "Mato Grosso" },
  { value: "MS", choice: "Mato Grosso do Sul" },
  { value: "GO", choice: "Goiás" },
  { value: "AC", choice: "Acre" },
  { value: "AL", choice: "Alagoas" },
  { value: "AP", choice: "Amapá" },
  { value: "AM", choice: "Amazonas" },
  { value: "BA", choice: "Bahia" },
  { value: "CE", choice: "Ceará" },
  { value: "ES", choice: "Espirito Santo" },
  { value: "MG", choice: "Minas Gerais" },
  { value: "MA", choice: "Maranhão" },
  { value: "PA", choice: "Pará" },
  { value: "PB", choice: "Paraíba" },
  { value: "PE", choice: "Pernambuco" },
  { value: "PI", choice: "Piauí" },
  { value: "RN", choice: "Rio Grande do Norte" },
  { value: "RO", choice: "Rôndonia" },
  { value: "RR", choice: "Roraima" },
  { value: "SE", choice: "Sergipe" },
  { value: "TO", choice: "Tocantins" },
];
